baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false

[params]
  #editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  #description = "Documentation for Hugo Learn Theme"
  #author = "Mathieu Cornic"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

  enableTeachableCSS = true
  enableTeachableJS = false

  showCopyableHTML = true # only if not server
  buildPopups = true # only if not server

[params.colors] # doesn't work in CSS

primary = '#FF8000'
secondary = '#00A651'
course_heading = '#ffffff'
navbar_fixed_text = '#ffffff'
heading = '#2b3636'
text = '#2b3636'
navbar_text = '#ffffff'
homepage_heading = '#ffffff'
video_player_color = '#00A651'

[params.debug]

missingWords = false
capitalization = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Authentic German Learning Academy"
description = "The best platform to learn German."
weight = 1
languageName = "English"

[Languages.de]
title = "Authentic German Learning Akademie"
description = "Die beste Plattform, um Deutsch zu lernen."
weight = 2
languageName = "Deutsch"

[taxonomies]
  category = "categories"